#!/usr/bin/python3

import evdev, evdev.ecodes as ecodes
import subprocess
import sys
import os
import time
import queue
import selectors
import pyudev
import logging

TS_DEV = "i2c-HDP0001:00"
TS_DRV_PATH = "/sys/bus/i2c/drivers/i2c_hid_acpi"

logging.basicConfig( encoding='utf-8', level=logging.DEBUG)

def disable_touchscreen():
    logging.info("Disable touchscreen")
    subprocess.run(f"echo {TS_DEV} > {TS_DRV_PATH}/unbind", shell=True, check=False)

def enable_touchscreen():
    logging.info("Enable touchscreen")
    subprocess.run(f"echo {TS_DEV} > {TS_DRV_PATH}/bind", shell=True, check=False)

def handle_input_event(event):
    logging.debug("event {}".format(event))

    if event.type == evdev.ecodes.EV_SW and event.code == evdev.ecodes.SW_TABLET_MODE:
        if event.value == 1:
            logging.info("Entering to tablet mode")
        else:
            logging.info("Exiting from tablet mode")

    if event.type == evdev.ecodes.EV_SW and event.code == evdev.ecodes.SW_LID:
        if event.value == 1:
            logging.info("Lid is closed, disabling touchscreen")
            disable_touchscreen()
        else:
            logging.info("Lid is opened, enabling touchscreen")
            enable_touchscreen()

monitored_devices = {}

context = pyudev.Context()

monitor = pyudev.Monitor.from_netlink(context)
monitor.filter_by('input')

device_events = queue.Queue()

def match_dev(device):
    if not device.sys_name.startswith("event"):
        return False

    try:
        ed = evdev.InputDevice(device.device_node)
        caps = ed.capabilities()

        if ecodes.EV_KEY in caps and ecodes.KEY_TOUCHPAD_OFF in caps[ecodes.EV_KEY] and ecodes.KEY_TOUCHPAD_ON in caps[ecodes.EV_KEY]:
            logging.info("Found evdev with touchpad ON/OFF capabilities: {}".format(device.device_node))
            return True

        if ecodes.EV_SW in caps and ecodes.SW_TABLET_MODE in caps[ecodes.EV_SW]:
            logging.info("Found evdev for tablet mode switch: {}".format(device.device_node))
            return True

        if ecodes.EV_SW in caps and ecodes.SW_LID in caps[ecodes.EV_SW]:
            logging.info("Found evdev for lid switch: {}".format(device.device_node))
            return True
    except:
        return False


def udev_event(action, device):
    logging.debug("udev: {} device: {}".format(action, device))

    if action == "add":
        if match_dev(device):
            device_events.put(('add', device))

    if action == "remove":
        device_events.put(('remove', device))


observer = pyudev.MonitorObserver(monitor, udev_event)
observer.start()

for device in context.list_devices(subsystem="input"):
    if match_dev(device):
        ed = evdev.InputDevice(device.device_node)
        monitored_devices[device.device_node] = ed

selector = selectors.DefaultSelector()
for node, ed in monitored_devices.items():
    selector.register(ed, selectors.EVENT_READ)


while True:
    select_events = selector.select(timeout=1)

    if len(select_events) == 0:
        while device_events.qsize() > 0:
            action, device = device_events.get()

            if action == "remove":
                if device.device_node in monitored_devices:
                    ed = monitored_devices[device.device_node]
                    selector.unregister(ed)
                    del monitored_devices[device.device_node]

            if action == "add":
                ed = evdev.InputDevice(device.device_node)
                monitored_devices[device.device_node] = ed
                selector.register(ed, selectors.EVENT_READ)

            device_events.task_done()

    for key, mask in select_events:
        device = key.fileobj

        try:
            event = device.read_one()
        except Exception as e:
            logging.info("Failed to read from {}".format(device))
            logging.info(e)
            selector.unregister(device)
            del monitored_devices[device.path]

        handle_input_event(event)

observer.stop()
